In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\jaswanth\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jaswanth\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\jaswanth\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\jaswanth\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\jaswanth\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\jaswanth\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd

In [6]:
data=[1,2,3,4,5]
index=['a','b','c','d','e']
series=pd.Series(data,index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['c1','c1','c2'],index=['r0','r1','r2'])
print(df)

    c1  c1  c2
r0   1   2   3
r1   4   5   6
r2   7   8   9

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, r0 to r2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      3 non-null      int64
 1   c1      3 non-null      int64
 2   c2      3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [9]:
df.describe()

        c1   c1   c2
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [10]:
obesity_data=pd.read_csv('./obesity_prediction.csv')

In [11]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [12]:
obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [13]:
obesity_data.head(30)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I
11,Female,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II
12,Male,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
13,Male,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I
14,Male,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
15,Female,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
16,Male,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
17,Female,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I
18,Female,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II
19,Female,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I
20,Male,22.0,1.65,80.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,3.0,2.0,no,Walking,Overweight_Level_II
21,Female,52.0,1.69,87.0,yes,yes,3.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I
22,Female,22.0,1.65,60.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Automobile,Normal_Weight
23,Female,22.0,1.60,82.0,yes,yes,1.0,1.0,Sometimes,no,2.0,no,0.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I
24,Male,21.0,1.85,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
25,Male,20.0,1.60,50.0,yes,no,2.0,4.0,Frequently,yes,2.0,no,3.0,2.0,no,Public_Transportation,Normal_Weight
26,Male,21.0,1.70,65.0,yes,yes,2.0,1.0,Frequently,no,2.0,no,1.0,2.0,Always,Walking,Normal_Weight
27,Female,23.0,1.60,52.0,no,yes,2.0,4.0,Frequently,no,2.0,no,2.0,1.0,Sometimes,Automobile,Normal_Weight
28,Male,19.0,1.75,76.0,yes,yes,3.0,3.0,Sometimes,no,2.0,yes,3.0,1.0,Sometimes,Public_Transportation,Normal_Weight
29,Male,23.0,1.68,70.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,2.0,Frequently,Walking,Normal_Weight

In [14]:
obesity_data.tail(15)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2096,Female,25.955014,1.626449,104.879602,yes,yes,3.0,3.0,Sometimes,no,2.094901,no,0.070890,0.599441,Sometimes,Public_Transportation,Obesity_Type_III
2097,Female,25.996716,1.626580,105.037203,yes,yes,3.0,3.0,Sometimes,no,2.347322,no,0.008013,0.503896,Sometimes,Public_Transportation,Obesity_Type_III
2098,Female,25.992348,1.606474,104.954291,yes,yes,3.0,3.0,Sometimes,no,2.331123,no,0.063383,0.561661,Sometimes,Public_Transportation,Obesity_Type_III
2099,Female,25.974446,1.628855,108.090006,yes,yes,3.0,3.0,Sometimes,no,1.757105,no,0.085119,0.465444,Sometimes,Public_Transportation,Obesity_Type_III
2100,Female,25.777565,1.628205,107.378702,yes,yes,3.0,3.0,Sometimes,no,2.506631,no,0.025787,0.484165,Sometimes,Public_Transportation,Obesity_Type_III
2101,Female,25.722004,1.628470,107.218949,yes,yes,3.0,3.0,Sometimes,no,2.487070,no,0.067329,0.455823,Sometimes,Public_Transportation,Obesity_Type_III
2102,Female,25.765628,1.627839,108.107360,yes,yes,3.0,3.0,Sometimes,no,2.320068,no,0.045246,0.413106,Sometimes,Public_Transportation,Obesity_Type_III
2103,Female,21.016849,1.724268,133.033523,yes,yes,3.0,3.0,Sometimes,no,1.650612,no,1.537639,0.912457,Sometimes,Public_Transportation,Obesity_Type_III
2104,Female,21.682367,1.732383,133.043941,yes,yes,3.0,3.0,Sometimes,no,1.610768,no,1.510398,0.931455,Sometimes,Public_Transportation,Obesity_Type_III
2105,Female,21.285965,1.726920,131.335786,yes,yes,3.0,3.0,Sometimes,no,1.796267,no,1.728332,0.897924,Sometimes,Public_Transportation,Obesity_Type_III
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [15]:
obesity_data.sample(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
671,Female,21.813083,1.712515,51.710723,yes,yes,2.881300,3.087544,Frequently,no,1.248180,no,1.952427,0.427461,no,Public_Transportation,Insufficient_Weight
1133,Male,34.098174,1.841151,91.798103,yes,yes,2.000000,2.997414,Sometimes,no,1.259454,no,0.935217,0.997600,Sometimes,Automobile,Overweight_Level_II
1953,Female,24.291205,1.711460,113.372851,yes,yes,3.000000,3.000000,Sometimes,no,2.796894,no,0.382189,0.167790,Sometimes,Public_Transportation,Obesity_Type_III
405,Male,18.000000,1.740000,86.000000,no,no,3.000000,3.000000,Sometimes,no,2.000000,no,3.000000,0.000000,no,Public_Transportation,Overweight_Level_II
1884,Female,26.000000,1.641918,111.868990,yes,yes,3.000000,3.000000,Sometimes,no,2.635454,no,0.000000,0.088309,Sometimes,Public_Transportation,Obesity_Type_III
878,Female,18.839190,1.624831,69.975607,yes,yes,2.253998,2.752318,Sometimes,no,2.328331,no,0.815509,0.024088,no,Public_Transportation,Overweight_Level_I
1309,Female,37.597953,1.629010,80.000000,yes,yes,2.450784,2.952821,Sometimes,no,1.335192,no,0.180276,0.000000,Sometimes,Automobile,Obesity_Type_I
578,Female,19.000000,1.530875,42.000000,no,no,2.844607,1.273128,Frequently,no,1.695510,no,0.260079,0.635867,Sometimes,Public_Transportation,Insufficient_Weight
1940,Female,26.000000,1.622468,110.400847,yes,yes,3.000000,3.000000,Sometimes,no,2.695094,no,0.000000,0.413474,Sometimes,Public_Transportation,Obesity_Type_III
129,Male,27.000000,1.700000,78.000000,no,yes,3.000000,3.000000,Sometimes,no,3.000000,no,1.000000,1.000000,Frequently,Public_Transportation,Overweight_Level_II

In [16]:
obesity_data.sample(10,random_state=29)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
631,Female,19.272573,1.713670,50.000000,no,yes,1.005578,4.000000,Frequently,no,1.000000,no,1.683957,0.704978,Sometimes,Public_Transportation,Insufficient_Weight
1216,Female,42.316070,1.583943,81.936398,yes,yes,2.490507,2.974204,Sometimes,no,1.846754,no,0.000000,0.000000,no,Automobile,Obesity_Type_I
1321,Female,23.000000,1.608469,82.954796,yes,yes,2.150054,2.988539,Sometimes,no,2.768325,no,2.085150,0.000000,no,Public_Transportation,Obesity_Type_I
1844,Female,26.000000,1.618573,104.928643,yes,yes,3.000000,3.000000,Sometimes,no,1.698767,no,0.000000,0.543960,Sometimes,Public_Transportation,Obesity_Type_III
820,Female,32.997118,1.672446,74.812707,yes,yes,2.948425,1.198643,Sometimes,no,1.000000,no,0.000000,0.173796,Sometimes,Automobile,Overweight_Level_I
2026,Female,21.838323,1.758959,137.792990,yes,yes,3.000000,3.000000,Sometimes,no,2.640539,no,1.879818,0.885993,Sometimes,Public_Transportation,Obesity_Type_III
692,Male,18.000000,1.767058,51.132809,yes,yes,2.708965,3.000000,Sometimes,no,1.873004,no,1.217180,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
454,Female,20.000000,1.680000,68.000000,no,yes,3.000000,1.000000,Sometimes,no,1.000000,no,1.000000,0.000000,no,Public_Transportation,Normal_Weight
875,Female,16.865984,1.644053,67.439589,yes,yes,1.314150,1.068196,Sometimes,no,1.364957,yes,0.000000,0.057926,no,Public_Transportation,Overweight_Level_I
1522,Male,28.363149,1.793476,112.725005,yes,yes,1.991240,3.000000,Sometimes,no,2.000000,no,0.000000,0.292956,Sometimes,Public_Transportation,Obesity_Type_II

In [17]:
obesity_data.columns.to_list()

['Gender',
 'Age',
 'Height',
 'Weight',
 'family_history',
 'FAVC',
 'FCVC',
 'NCP',
 'CAEC',
 'SMOKE',
 'CH2O',
 'SCC',
 'FAF',
 'TUE',
 'CALC',
 'MTRANS',
 'Obesity']

In [18]:
obesity_data.index

RangeIndex(start=0, stop=2111, step=1)

In [19]:
obesity_data.shape

(2111, 17)

In [20]:
obesity_data.size

35887

In [22]:
obesity_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [23]:
obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2111 non-null   object
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object
 5   FAVC            2111 non-null   object
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object
 9   SMOKE           2111 non-null   object
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object
 15  MTRANS          2111 non-null   object
 16  Obesity         2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [25]:
obesity_data.loc[0:10,'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
0,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0
1,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0
2,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0
3,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0
4,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0
5,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0
6,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
7,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0
8,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
9,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0
10,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0

In [26]:
obesity_data.iloc[[10,20,30],[0,1,2]]

   Gender   Age  Height
10   Male  26.0    1.85
20   Male  22.0    1.65
30   Male  29.0    1.77

In [27]:
obesity_data.at[0,'Age']

21.0

In [28]:
obesity_data.iat[0,5]

'no'